src/deploymentizer, test/functional/deploymentizer.spec.js
Fixes an issue with the shell script used to start app. Adds test to check for valid script.
=> fix for the shell script and test

README.md, src/deploymentizer, src/lib/deploymentizer.js, src/lib/generator.js, test/functional/lib/deploymentizer.spec.js
Allows deploymentizer to restrict the clusters generated to a specific type.
=> Genesis 856/add type

package.json, src/deploymentizer, src/lib/deploymentizer.js, test/functional/lib/deploymentizer.spec.js, test/unit/lib/deploymentizer.spec.js
- Adds support for our transition to our Elroy service
=> Adding integration with elroy for transition phase

README.md, src/deploymentizer, src/lib/deploymentizer.js
- Adds ability to specify the exact cluster name you want to generate for
=> feat: ability to filter by clusterName

src/lib/deploymentizer.js
- updating our elroy sync for the transition
=> feat: pass all metadata and the entire resourceConfig to elroy

src/lib/deploymentizer.js
=> logging when  tier  doesn't exist but not throws an error

src/lib/deploymentizer.js, test/functional/lib/deploymentizer.spec.js
Actually, enable the Elroy deactivation of clusters during syncing.
=> enable elroy environment-level sync

src/.eslintrc, src/lib/elroy-sync.js, test/.eslintrc, test/unit/lib/resources-sync.spec.js
https://github.com/InVisionApp/elroy/issues/262
=> Sync config with branch

src/lib/elroy-sync.js, test/unit/lib/resources-sync.spec.js
https://github.com/InVisionApp/elroy/issues/262
=> checking resources are populated from cluster definition

test/unit/lib/resources-sync.spec.js
=> Testing sync resources loaded from Yaml 

package.json, src/lib/deploymentizer.js, test/unit/plugin/env-api-client.spec.js
- allow passing both clusterName and clusterType
- updated eslint and prettier versions
=> Remove type and name check

Dockerfile
https://github.com/InVisionApp/kit-server/issues/211
InVisionApp/engineering-velocity#390
=> bumping nodejs version

package.json, src/lib/elroy-sync.js, test/unit/lib/elroy-sync.spec.js
https://github.com/InVisionApp/elroy/issues/382
=> Sync - don't  create deployment-env if doesn't exists  

src/lib/deploymentizer.js, src/plugin/env-api-client-v3.js, src/plugin/env-api-client.js, src/util/event-handler.js, test/unit/lib/elroy-sync.spec.js, test/unit/plugin/env-api-client-v3.spec.js, test/unit/plugin/env-api-client.spec.js
https://github.com/InVisionApp/engineering-velocity/issues/678
=> adding metrics/events to envapi calls

src/lib/deploymentizer.js
InVisionApp/engineering-velocity#678
=> asign events properly to plugin

src/lib/generator.js, test/unit/lib/generator.spec.js
#78 
https://github.com/InVisionApp/engineering-velocity/issues/712
=> checking containers len

src/lib/generator.js, test/unit/lib/generator.spec.js
inVisionApp/engineering-velocity#712
=> setting default img for non-primary containers

src/lib/generator.js
https://github.com/InVisionApp/engineering-velocity/issues/712
=> skipping primary and image SHA for HPAs

src/lib/deploymentizer.js, src/plugin/env-api-client-v3.js, test/unit/plugin/env-api-client-v3.spec.js
https://github.com/InVisionApp/project-xb500/issues/964
=> 206 failed deploy - missing env with launchdarkly

src/lib/generator.js
return fseMkdirs so that we're waiting for directory creation
=> Directory Creation Promise fix

src/plugin/env-api-client-v3.js
- fixing an issue where we'd return before the promise resolved
- re-organizing function calls
- adding a tags property to the class with helper functions for setting, getting and updating the tags objects
=> EV-1412 - Ensure we don't return before the ld promise is resolved

src/lib/generator.js, src/plugin/env-api-client-v3.js, test/unit/plugin/env-api-client-v3.spec.js
- updating tests to check for gitRef parameter
- adding a function to determine gitRef
- passing in commitId in the argument service object
=> EV-1579 - gitRef fix for envapi plugin

src/plugin/env-api-client-v3.js, test/unit/plugin/env-api-client-v3.spec.js
- parse error base off API version
- adding tests to confirm this behavior
- fix a spot where we weren't returning a promise
Resolves https://invisionapp.atlassian.net/browse/EV-1598
=> EV-1598 - Fix v4 Partial Response errors
